1. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [2]:
import numpy as np
arr=np.array([1,2,3,6,4,5])
print(arr[::-1])

[5 4 6 3 2 1]


2. Compare the following numpy arrays: arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
print(np.array_equal(arr1,arr2))

True


3. Find the most frequent value and their indice(s) in the following arrays:
i.
x = np.array([1,2,3,4,5,1,2,1,1,1])
ii.
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [3]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
most_freq = np.bincount(x).argmax()
indices = np.where(x== most_freq)[0]

print("Most frequent value:", most_freq)
print("Indices:", indices)


Most frequent value: 1
Indices: [0 5 7 8 9]


In [4]:
y=np.array([1,1,1,2,3,4,2,4,3,3,])
most_freq = np.bincount(y).argmax()
indices = np.where(y== most_freq)[0]

print("Most frequent value:", most_freq)
print("Indices:", indices)

Most frequent value: 1
Indices: [0 1 2]


4. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'),
find
i. Sum of all elements
ii.Sum of all element’s row-wise
iii.Sum of all element’s column-wise



In [ ]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
sum=gfg.sum()
print(sum)

45


In [ ]:
row_sum=gfg.sum(axis=1)
print(row_sum)

[[14]
 [16]
 [15]]


In [ ]:
col_sum=gfg.sum(axis=0)
print(col_sum)

[[20  9 16]]
